import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${inter.className} h-full antialiased`}>
			<body className="min-h-screen bg-[#09090B]">
				<ClerkProvider>
					<main className="flex-1 min-w-0">{children}</main>
				</ClerkProvider>
			</body>
		</html>
	);
}
